spring:
  profiles:
    active: localhost
---
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/testdb
    username: test
    password: test
    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://db/testdb
    username: test
    password: test
    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace
