spring:
  datasource:
    url: jdbc:mysql://localhost:3307/testdb
    username: test
    password: test
    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace
